.TH slepos-plugin "8" "17 Jul 2010" "slepos-plugin" "Support Utilities Manual"
.SH NAME
slepos-plugin \- SUSE Linux Enterprise Point of Service Plugin for 
.BR supportconfig (8)
.
.SH DESCRIPTION
Supportconfig plugins add functionality to the supportconfig script. This plugin extends supportconfig's functionality to include SUSE LINUX Enterprise Point of Service 
information. Supportconfig saves the plugin output as plugin-slepos.txt.

.SH FILES
.I /opt/supportconfig/plugins/slepos
.RS
The SLEPOS plugin
.RE
.SH AUTHOR
Jason Record <jrecord@novell.com>
.SH REPORTING BUGS
Please submit bug fixes, comments or enhancement requests via: 
.B http://code.google.com/p/supportutils-plugin-slepos/issues/list
.SH SEE ALSO
.BR supportconfig (8)
.BR supportconfig.conf (5)
