.TH susestudio-plugin "8" "21 Oct 2010" "susestudio-plugin" "Support Utilities Manual"
.SH NAME
susestudio-plugin \- SUSE Studio Plugin for 
.BR supportconfig (8)
.
.SH DESCRIPTION
Supportconfig plugins add functionality to the supportconfig script. This plugin extends supportconfig's functionality to include SUSE Studio
information. Supportconfig saves the plugin output as plugin-susestudio.txt.

.SH FILES
.I /usr/lib/supportconfig/plugins/susestudio
.RS
The SUSE Studio plugin
.RE
.SH AUTHOR
Jason Record <jrecord@novell.com>
.SH REPORTING BUGS
Please submit bug fixes, comments or enhancement requests via: 
.B http://code.google.com/p/supportutils-plugin-susestudio/issues/list
.SH SEE ALSO
.BR supportconfig (8)
.BR supportconfig.conf (5)
